### ISSUE TITLE
ProtoSpace挙動確認

### ISSUE THREAD

**Issue by JackieZHU316** [JackieZHU316/protospace-37930#1]
URLは下記のようになります。よろしくお願いいたします。
https://protospace-37930.herokuapp.com/

**Comment by shodai-ito** [comment]
@JackieZHU316 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメントの投稿者名をクリックすると、プロトタイプの投稿者のページに遷移してしまいます。

### **`その他`**
- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
ログアウト状態では全てのページにアクセスできなくなっています。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by JackieZHU316** [comment]
ご連絡ありがとうございました。
上記の内容を修正し本番作業で動作チェックを行いました。
大変お手数ですが、ご確認の作業をよろしくお願いいたします。

作業の失敗について、下記の要因だと思いました。
１：ユーザー詳細ページと投稿者ページ混乱してまいました。確認不足ですみません。
２：「ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること」趣旨をうまく理解できなかったので、スルーしてしまいました。
３：焦ってしまい、作業効率が悪くなってしまいました。

**Comment by shodai-ito** [comment]
@JackieZHU316 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by JackieZHU316** [comment]
ご連絡ありがとうございました！
大変嬉しく思います！😊
まだまだたくさん課題残ってますが、最後までやっていきたいと思います！
